theme: jekyll-theme-minimal
logo: WhatsApp Image 2020-09-26 at 09.32.13.jpeg
title: Diala Al Masri
description: I am a PhD student at the University of Oxford and my field is labor economics. I am working under the supervision of professors Gabriel Ulyssea and Douglas Gollin. #Here is my <a href="CV.pdf">CV</a>.
